# Generated by Django 4.2.5 on 2023-09-16 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Visibility', models.CharField(choices=[('private', 'private'), ('public', 'public')], max_length=20)),
                ('bg_color', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ManyToManyField(blank=True, null=True, related_name='team_board', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
