# Generated by Django 4.2.5 on 2023-09-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_board_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='bg_color',
        ),
    ]
